package org.example.socialmediaapp.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonMerge;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
public class Post {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String  id;
    private String text;

    private String image;

    private int likes = 0;
    private String link;

    @ElementCollection
    private List<String> tags;

    private LocalDateTime publishDate = LocalDateTime.now(); // date autogenerated

    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonBackReference
    private User user;

    @OneToMany(mappedBy = "post",cascade = CascadeType.ALL)
    @JsonManagedReference
    private List<Comment> comments;

    public Post() {}

    public Post(String id, User user, LocalDateTime publishDate, List<String> tags, String link, int likes, String image, String text) {
        this.id = id;
        this.user = user;
        this.publishDate = publishDate;
        this.tags = tags;
        this.link = link;
        this.likes = likes;
        this.image = image;
        this.text = text;
    }

    public String getId() {
        return id;
    }

    public String getText() {
        return text;
    }

    public String getImage() {
        return image;
    }

    public int getLikes() {
        return likes;
    }

    public String getLink() {
        return link;
    }

    public LocalDateTime getPublishDate() {
        return publishDate;
    }

    public List<String> getTags() {
        return tags;
    }

    public User getUser() {
        return user;
    }

    public void setText(String text) {
        this.text = text;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public void setPublishDate(LocalDateTime publishDate) {
        this.publishDate = publishDate;
    }

    public void setOwner(User user) {
        this.user = user;
    }

}
