package org.example.socialmediaapp.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonMerge;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
public class Post {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String  id; // id autogenerated
    private String text;
    @Column
    // texte 6-1000 caractères

    private String image; // URL de l'image

    private int likes = 0; // valeur initiale 0

    @Column
    private String link; // URL de lien 6-200 caractères

    @ElementCollection
    private List<String> tags; // tableau de tags

    private LocalDateTime publishDate = LocalDateTime.now(); // date autogenerated

    @ManyToOne
    @JoinColumn(name = "owner_id")
    @JsonManagedReference
    private User owner; // objet User Preview

    // Getters et Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getText() { return text; }
    public void setText(String text) { this.text = text; }

    public String getImage() { return image; }
    public void setImage(String image) { this.image = image; }

    public int getLikes() { return likes; }
    public void setLikes(int likes) { this.likes = likes; }

    public String getLink() { return link; }
    public void setLink(String link) { this.link = link; }

    public List<String> getTags() { return tags; }
    public void setTags(List<String> tags) { this.tags = tags; }

    public LocalDateTime getPublishDate() { return publishDate; }
    public void setPublishDate(LocalDateTime publishDate) { this.publishDate = publishDate; }

    public User getOwner() { return owner; }
    public void setOwner(User owner) { this.owner = owner; }
}
